version: "3.7"
services:
  balancer:
    ports:
      - "8080:8080"
    volumes:
      - ./traefik/dynamic.toml:/etc/traefik/dynamic.toml
      - ./traefik/certs:/etc/certs # SSL Development certificates

  nginx:
    ports:
      - "80:80"

  micado_db:
    ports:
      - "5432:5432"

  data_api:
    ports:
      - "3000:3000"

  db_admin:
    ports:
      - "82:80"

  api_gateway:
    ports:
      - "8280:8280"
      - "8243:8243"
      - "9443:9443"

  identity_server:
    ports:
      - "9763:9763"
      - "9443:9443"

  countly_frontend:
    ports:
      - "6001:6001"

  countly_api:
    ports:
      - "3001:3001"

  mongo-express:
    ports:
      - 8081:8081

  chatbot:
    ports:
      - 5005:5005

  portainer:
    ports:
      - 9000:9000

  weblate:
    ports:
      - 81:8080

  git:
    ports:
      - "3000:3000"
      - "222:22"

  sequelize:
    image: micadoproject/auto_sequelize
    command: "sh -c 'sequelize-automate -t js -h micado_db -d micado -u micadoapp -p micadoapp -P 5432  -e postgres -o /code '"
    env_file:
      - prod.env
    environment:
      PGRST_DB_URI: postgres://${MICADO_DB_PWD}:${MICADO_DB_USER}@micado_db:5432/${POSTGRES_DB}
      PGRST_DB_SCHEMA: ${MICADO_DB_SCHEMA}
      PGRST_DB_ANON_ROLE: ${MICADO_DB_USER} #In production this role should not be the same as the one used for the connection
    volumes:
      - sequelize:/code
    networks:
      - micado_net

volumes:
  sequelize:
    driver: local
    driver_opts:
      type: none
      # device is the path in the host that has to be absolute
      device: $PWD/sequelize
      o: bind
